config/routes.rb
ChaseBlog::Application.routes.draw do

  # get "admins/show"
  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  get '/admins' => 'admins#show'
  
  get '/home' => 'static_pages#home'
  get '/resources' => 'static_pages#resources'
  get '/about' => 'static_pages#about'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :posts

  has_many :comments

  before_save { self.email = email.downcase }
 #  attr_accessor :password
	before_create :create_remember_token # this is a callback method to create a remember token immediately nefore creating a new user in the database

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } 
  validates :password, length: { minimum: 6 }
	has_secure_password

	def Admin.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Admin.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    # this method is only used internally by the Admin model, so no need to expose it to outside users
    def create_remember_token
      self.remember_token = Admin.digest(Admin.new_remember_token) # the self keyword assigns the method to one of the admins attributes
      # without the self assignment there would be an local variable called remember_token
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :category_posts
	has_many :posts, through: :category_posts
end

app/models/category_post.rb
class CategoryPost < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :admin
	belongs_to :user
	
	# has_many :comments
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :admin
	has_many :category_posts
	has_many :categories, through: :category_posts
	has_many :comments
	
	default_scope -> { order('created_at DESC') }
	validates :content, presence: true, length: { maximum: 5000 }
	validates :admin_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :signed_in_admin, only: [:show]

	def show
		@admin = Admin.find(params[:id])
		# this needs to route to the post creation page.  Which is only
		# accessed through sessions and can be seen as the "profile page"
	end

	def new 
	end

	def create
	end

	private

		def signed_in_admin
			redirect_to signin_url, notice: "Please sign in." unless signed_in?
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
 
  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_admin
    @_current_admin ||= session[:current_admin_id] &&
      Admin.find_by(id: session[:current_admin_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	 	admin = Admin.find_by(email: params[:session][:email].downcase) # pulls the admin out of the db using the submitted email address
    if admin && admin.authenticate(params[:session][:password]) # this is only true if both admin and admin.authenticate are true
     	sign_in admin
     	redirect_to admin # use admin not admin path
      # Sign the admin in and redirect to the admin's show page.
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

	def destroy
    sign_out
    redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	def show
  		@posts = @admin.posts.paginate(page: params[:page])
  	end
  end

  def resources
  end

  def about
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "JCD"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(admin)
    remember_token = Admin.new_remember_token # create new token
    cookies.permanent[:remember_token] = remember_token # place raw token in the browser cookies
    admin.update_attribute(:remember_token, Admin.digest(remember_token)) # save the hashed token to the database
    # update_attribute updates a single attribute while bypassing validations 
    self.current_admin = admin # set the current admin equal to the given admin
  end

  def signed_in?
  	!current_admin.nil?
  end

  def current_admin=(admin)
  	@current_admin = admin
  end

  def current_admin
    remember_token = Admin.digest(cookies[:remember_token])
    @current_admin ||= Admin.find_by(remember_token: remember_token)
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_admin = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/show.html.erb
<% provide(:title, 'Admin') %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>Create Posts</h1>
				<p>
					<%= @admin.email %>
				</p>
		</section>
	</aside>
</div>


	

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<p>Developed by Aaron Flower</p>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Resources", resources_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Sign in", signin_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "JCD Blog", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Resources", resources_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Admins", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Admin Page", current_admin %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title><%= full_title(yield(:title)) %></title>
  		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
		</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
        		<div class="alert alert-<%= key %>"><%= value %></div>
      		<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/posts/_post.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if @admin.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@admin.errors.count, "error") %>.
    </div>
    <ul>
    <% @admin.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
	<p>
		This page will be about Chase and The Well
	</p>

app/views/static_pages/home.html.erb
<!-- <div class="center hero-unit">
<h1>Blog</h1>
	<p>
		This is where a blog will be
	</p>
</div>
 -->

<div class="row">
	<aside>
		
	</aside>
	<div class="span8">
		<% if @admin.posts.any? %>
			<h3>Posts (<%= @admin.posts.count %>)</h3> 
			<ol class="posts">
				<%= render @posts %>
			</ol>
			<%= will_paginate @posts %> 
		<% end %>
	</div>
</div>

app/views/static_pages/resources.html.erb
<% provide(:title, 'Resources') %>
<h1>Resources</h1>
  <p>
    This page will have books and web sites resources
  </p>